Add Stape logging format. Closes #5
PiwikPRO/server-side-template-for-gtm-v2 pull request #6
Opened 2024-08-02 12:33 UTC by Bukashk0zzz

Add Stape logging format.

2024-08-07 08:59 UTC, sahava requested changes

2024-08-07 08:59 UTC, sahava commented on template.tpl
> +const getContainerVersion = require('getContainerVersion');
Move these two `const` declarations to correct positions in the API list (alphabetical order).

2024-08-07 08:59 UTC, sahava commented on template.tpl
> +const isLoggingEnabled = determinateIsLoggingEnabled();
Move up to list of consts, change to capital case, use renamed function:

```
const LOGGING_ENABLED = isLoggingEnabled();
```

2024-08-07 08:59 UTC, sahava commented on template.tpl
> +const traceId = isLoggingEnabled ? getRequestHeader('trace-id') : undefined;
Change to `const traceId = LOGGING_ENABLED ? ...`

2024-08-07 08:59 UTC, sahava commented on template.tpl
> +function determinateIsLoggingEnabled() {
Change to `const` like other function declarations and rename to `isLoggingEnabled`:

```
const isLoggingEnabled = () => {
```

2024-08-07 08:59 UTC, sahava commented on template.tpl
> +const headers = {
move this to where the other constants are declared, and use capital case 

```
const HEADERS = {
  ...
}
```

2024-08-07 08:59 UTC, sahava commented on template.tpl
> +if (isLoggingEnabled) {
Change to `if (LOGGING_ENABLED) {`

2024-08-07 08:59 UTC, sahava commented on template.tpl
> +  headers: headers,
Change to `headers: HEADERS`

2024-08-07 08:59 UTC, sahava commented on template.tpl
> +  if (isLoggingEnabled) {
Change to `if (LOGGING_ENABLED) {`

2024-08-07 12:34 UTC, sahava commented on template.tpl
> +        TraceId: traceId,
Update to `TraceId: TRACE_ID`

2024-08-07 12:34 UTC, sahava commented on template.tpl
> +        RequestHeaders: headers,
Update to `RequestHeaders: HEADERS`

2024-08-07 12:35 UTC, sahava commented on template.tpl
> +          TraceId: traceId,
Update to `TraceId: TRACE_ID`

2024-08-07 16:43 UTC, Bukashk0zzz commented
@sahava Thanks for the review and all your fixes.

2024-08-08 08:12 UTC, abartczakpiwik approved these changes

2024-08-08 08:34 UTC, sahava approved these changes

2024-08-08 08:36 UTC, merged